# Site settings
title: aktor-e
email: contact@aktor-e.com
description: aktor-e develops factory intelligence software for predictive maintenance, energy efficiency, and operation analytics in the era of Industry 4.0 and manufacturing digital twins. > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.aktor-e.com" # the base hostname & protocol for your site

phone_number: +49 178 790 6554

# Build settings
markdown: kramdown
